sudo: required

language: c

services:
  - docker

before_install:
  - docker build -f Dockerfile -t atgreen/greenfx-kairosdb .

script:
- 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/greenfx-kairosdb;
    fi
  - echo All done.
